const actions = {
  GET_ALL_TABS: 'GET_ALL_TABS',
  GET_STATES: 'GET_STATES',
  TAB_SELECTED: 'TAB_SELECTED',
  CLASS_SELECTED: 'CLASS_SELECTED',
  SAMPLE_LENGTH_CHANGED: 'SAMPLE_LENGTH_CHANGED',
  SWITCH_CHANGED: 'SWITCH_CHANGED'
}

export default actions