const ACTIONS = {
  GET_ALL_TABS: 'GET_ALL_TABS',
  GET_STATES: 'GET_STATES',
  TAB_SELECTED: 'TAB_SELECTED',
  CLASS_SELECTED: 'CLASS_SELECTED',
  SAMPLE_LENGTH_CHANGED: 'SAMPLE_LENGTH_CHANGED',
  SWITCH_CHANGED: 'SWITCH_CHANGED',
  START_COLLECTING_DATA: 'START_COLLECTING_DATA',
  STOP_COLLECTING_DATA: 'STOP_COLLECTING_DATA',
  RTC_PEER_CONNECTION_OFFER: 'RTC_PEER_CONNECTION_OFFER',
  RTC_PEER_CONNECTION_ANSWER: 'RTC_PEER_CONNECTION_ANSWER',
  RTC_PEER_CONNECTION_ADD_CANDIDATE: 'RTC_PEER_CONNECTION_ADD_CANDIDATE',
  RTC_PEER_CONNECTION_CLIENT: 'RTC_PEER_CONNECTION_CLIENT'
}

export default ACTIONS
