const CONSTANTS = {
  CHLOE: 'CHLOE',
  BEEP: 'BEEP',
  MUSIC: 'MUSIC',
  EVENTS: {
    START_PREDICTING: 'START_PREDICTING',
    STOP_PREDICTING: 'STOP_PREDICTING'
  },
  WEB_RTC_EVENTS: {
    PEER_CONNECTION_SENDER_READY: 'PEER_CONNECTION_SENDER_READY',
    PEER_CONNECTION_RECEIVER_READY: 'PEER_CONNECTION_RECEIVER_READY',
    PEER_CONNECTION_OFFER: 'PEER_CONNECTION_OFFER',
    PEER_CONNECTION_ANSWER: 'PEER_CONNECTION_ANSWER',
    PEER_CONNECTION_RECEIVER_CANDIDATE: 'PEER_CONNECTION_RECEIVER_CANDIDATE',
    PEER_CONNECTION_SENDER_CANDIDATE: 'PEER_CONNECTION_SENDER_CANDIDATE',
    PEER_CONNECTION_ERROR: 'PEER_CONNECTION_ERROR',
    PEER_CONNECTION_CLOSE: 'PEER_CONNECTION_CLOSE'
  },
  PORTS: {
    WEB_RTC: 'WEB_RTC',
    CROSS_LAYER: 'CROSS_LAYER'
  },
  DEFAULT_SAMPLE_LENGTH: 700,
  TARGET_FRAME_LENGTH: 0.025, // 25 milliseconds
  N_MFCC: 13,
  CLASS_TO_NUMBER: {
    CHLOE: 0,
    BEEP: 1,
    MUSIC: 2
  },
  AUDIO_FEATURES: {
    SINGLE_VALUE: [
      'rms',
      'energy',
      'spectralCentroid',
      'spectralFlatness',
      'spectralRolloff',
      'spectralSkewness',
      'perceptualSpread',
      'perceptualSharpness'
    ],
    ARRAY: ['mfcc', 'powerSpectrum']
  },
  LATENCY_TIME_TO_DELETE_DATASET: 1000 // ms
}

export default CONSTANTS
